application:
    resource:
        path: ../src/Presentation/Http/Action
        namespace: BetterMe\TestAssigment\Presentation\Http\Action
    type: attribute

mock_api:
    resource:
        path: ../src/MockApi
        namespace: BetterMe\TestAssigment\MockApi
    type: attribute
