# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    better_me.test_assigment.base_url: '%env(BASE_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    BetterMe\TestAssigment\:
        resource: '../src/'
        exclude:
            - '../src/Domain/ValueObject/'
            - '../src/Infrastructure/Symfony/Kernel.php'

    BetterMe\TestAssigment\Presentation\Http\Action\:
        resource: '../src/Presentation/Http/Action'
        tags: [ 'controller.service_arguments' ]

    BetterMe\TestAssigment\MockApi\:
        resource: '../src/MockApi'
        tags: [ 'controller.service_arguments' ]

    BetterMe\TestAssigment\Infrastructure\Symfony\ValueResolver\UuidValueResolver:
        tags:
            - controller.argument_value_resolver:
                  priority: 101

    Symfony\Contracts\HttpClient\HttpClientInterface:
        factory: [ 'Symfony\Component\HttpClient\HttpClient', 'create' ]
        arguments:
            - base_uri: '%better_me.test_assigment.base_url%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
